services:
    redis-cache:
        image: redis:alpine
        container_name: montrack-redis-cache
        ports:
            -   "6379:6379"
    backend-app:
        container_name: montrack-backend-app
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8081:${APP_PORT}"
